version = 0.1
[aambrizb.deploy.parameters]
stack_name = "sam-api-lambda"
resolve_s3 = true
s3_prefix = "sam-api-lambda"
region = "mx-central-1"
profile = "aambrizb"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
