AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-api-lambda

  Example AWS SAM Template API Lambda

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /helloworld
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway EndPoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/helloworld/"
  HelloWorldFunction:
    Description: "HelloWorld Lambda API Function ARN"
    Value: !GetAtt HelloWorldAPIFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM HelloWorld"
    Value: !GetAtt HelloWorldAPIFunctionRole.Arn
