version = 0.1
[aambrizb.deploy.parameters]
stack_name = "sam-aurora-psql-serverless"
resolve_s3 = true
s3_prefix = "sam-aurora-psql-serverless"
region = "us-east-1"
profile = "aambrizb"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
